services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./startup_sql:/docker-entrypoint-initdb.d/
    ports:
      - "5439:5432"
  
  dataloader:
    image: python:3.12-slim
    secrets:
      - db_password
    environment:
      - PYTHONUNBUFFERED=1
      
    depends_on:
      - db
    volumes:
      - ./dataloader:/app
    working_dir: /app
    command: sh -c "pip install -r requirements.txt && python main.py"

  web:
    image: python:3.12-slim
    restart: always
    secrets:
      - db_password
    environment:
      - PYTHONUNBUFFERED=1
      - DB_USER=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=hash_store
    depends_on:
      - dataloader
    volumes:
      - ./webapp:/app
      - ./README.md:/app/README.md:ro
    working_dir: /app
    ports:
      - "8085:8080"
    command: sh -c "pip install -r requirements.txt && python app.py"



volumes:
  db_data:
    driver: local

    
secrets:
  db_password:
    file: ./secrets/db_password.txt

